// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_L_7QuX1uDGhPHUAFSsf2Td1W3J3zkb8',
    appId: '1:130377137924:web:768e9cba1230d8ad6c9a51',
    messagingSenderId: '130377137924',
    projectId: 'sasae-notification',
    authDomain: 'sasae-notification.firebaseapp.com',
    storageBucket: 'sasae-notification.appspot.com',
    measurementId: 'G-0M51DEMSBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPoYKKiJKNLR3whzp3iXyaAzhQoUCpH6U',
    appId: '1:130377137924:android:3e230dff319e8baa6c9a51',
    messagingSenderId: '130377137924',
    projectId: 'sasae-notification',
    storageBucket: 'sasae-notification.appspot.com',
  );
}
