@startuml
set namespaceSeparator ::

class "sasae_flutter_app::api_config.dart::HostingMode" {
  +int index
  {static} +List<HostingMode> values
  {static} +HostingMode local
  {static} +HostingMode ip
  {static} +HostingMode internet
}

"sasae_flutter_app::api_config.dart::HostingMode" o-- "sasae_flutter_app::api_config.dart::HostingMode"
"dart::core::Enum" <|-- "sasae_flutter_app::api_config.dart::HostingMode"

class "sasae_flutter_app::firebase_options.dart::DefaultFirebaseOptions" {
  {static} +FirebaseOptions web
  {static} +FirebaseOptions android
  {static} +FirebaseOptions currentPlatform
}

"sasae_flutter_app::firebase_options.dart::DefaultFirebaseOptions" o-- "firebase_core_platform_interface::firebase_core_platform_interface.dart::FirebaseOptions"

class "sasae_flutter_app::main.dart::MyApp" {
  +AdaptiveThemeMode? savedThemeMode
  +State<MyApp> createState()
}

"sasae_flutter_app::main.dart::MyApp" o-- "adaptive_theme::src::adaptive_theme_mode.dart::AdaptiveThemeMode"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::main.dart::MyApp"

class "sasae_flutter_app::main.dart::_MyAppState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::main.dart::_MyAppState"

class "sasae_flutter_app::models::auth.dart::AuthModel" {
  +String tokenKey
  +String group
  +int accountID
  +int profileID
  +int hashCode
  +AuthModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "sasae_flutter_app::models::bank.dart::BankModel" {
  +String bankName
  +String bankBranch
  +String bankBSB
  +String bankAccountName
  +String bankAccountNumber
  +int hashCode
  +BankModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "sasae_flutter_app::models::ngo.dart::NGOModel" {
  +double latitude
  +double longitude
  +String orgName
  +DateTime estDate
  +List<String> fieldOfWork
  +String address
  +String? epayAccount
  +BankModel? bank
  +String? swcCertificateURL
  +String? panCertificateURL
  +int hashCode
  +NGOModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"sasae_flutter_app::models::ngo.dart::NGOModel" o-- "sasae_flutter_app::models::bank.dart::BankModel"
"sasae_flutter_app::models::user.dart::UserModel" <|-- "sasae_flutter_app::models::ngo.dart::NGOModel"

class "sasae_flutter_app::models::ngo_.dart::NGO_Model" {
  +int ngoID
  +String orgName
  +String orgPhoto
  +DateTime estDate
  +List<String> fieldOfWork
  +String address
  +int hashCode
  +NGO_Model copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "sasae_flutter_app::models::notification.dart::NotificationModel" {
  +int id
  +String title
  +String body
  +NotificationChannel channel
  +PostType? postType
  +int? postID
  +bool isRead
  +int hashCode
  +NotificationModel copyWith()
  +Map<String, dynamic> toMap()
  {static} +NotificationChannel getNotificationChannel()
  {static} +PostType getPostType()
  +String toJson()
  +String toString()
  +bool ==()
}

"sasae_flutter_app::models::notification.dart::NotificationModel" o-- "sasae_flutter_app::services::notification_service.dart::NotificationChannel"
"sasae_flutter_app::models::notification.dart::NotificationModel" o-- "sasae_flutter_app::providers::post_provider.dart::PostType"

class "sasae_flutter_app::models::people.dart::PeopleModel" {
  +String fullname
  +String gender
  +DateTime birthDate
  +String address
  +String? citizenshipPhoto
  +int hashCode
  +PeopleModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"sasae_flutter_app::models::user.dart::UserModel" <|-- "sasae_flutter_app::models::people.dart::PeopleModel"

class "sasae_flutter_app::models::people.dart::PeopleUpdateModel" {
  -String? _fullname
  -String? _gender
  -DateTime? _birthDate
  -String? _address
  -String? _phone
  -String? _email
  -bool? _isVerified
  -XFile? _citizenshipPhoto
  -XFile? _displayPicture
  -String? _citizenshipPhotoLink
  -String? _displayPictureLink
  +String? getFullname
  +String? getGender
  +DateTime? getBirthDate
  +String? getAddress
  +String? getPhone
  +String? getEmail
  +bool? getIsverified
  +XFile? getCitizenshipPhoto
  +XFile? getDisplayPicture
  +String? getCitizenshipPhotoLink
  +String? getDisplayPictureLink
  +String? setFullname
  +String? setGender
  +DateTime? setBirthDate
  +String? setAddress
  +String? setPhone
  +String? setEmail
  +XFile? setCitizenshipPhoto
  +XFile? setDisplayPicture
  +void nullifyAll()
  +String toString()
}

"sasae_flutter_app::models::people.dart::PeopleUpdateModel" o-- "cross_file::src::types::interface.dart::XFile"

abstract class "sasae_flutter_app::models::post::abstract_post.dart::AbstractPostModel" {
  +int id
  +String? author
  +int? authorID
  +List<String> relatedTo
  +String postContent
  +DateTime createdOn
  +DateTime? modifiedOn
  +bool isAnonymous
  +String postType
  +List<NGO__Model> pokedNGO
}

class "sasae_flutter_app::models::post::ngo__.dart::NGO__Model" {
  +int id
  +String orgName
  +String orgPhoto
  +int hashCode
  +NGO__Model copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "sasae_flutter_app::models::post::normal_post.dart::NormalPostModel" {
  +String? attachedImage
  +List<int> upVote
  +List<int> downVote
  +bool upVoted
  +bool downVoted
  +String? author
  +int? authorID
  +DateTime createdOn
  +int id
  +bool isAnonymous
  +DateTime? modifiedOn
  +List<NGO__Model> pokedNGO
  +String postContent
  +String postType
  +List<String> relatedTo
  +int hashCode
  +NormalPostModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"sasae_flutter_app::models::post::abstract_post.dart::AbstractPostModel" <|-- "sasae_flutter_app::models::post::normal_post.dart::NormalPostModel"

class "sasae_flutter_app::models::post::normal_post.dart::NormalPostReactionType" {
  +int index
  {static} +List<NormalPostReactionType> values
  {static} +NormalPostReactionType upVote
  {static} +NormalPostReactionType downVote
}

"sasae_flutter_app::models::post::normal_post.dart::NormalPostReactionType" o-- "sasae_flutter_app::models::post::normal_post.dart::NormalPostReactionType"
"dart::core::Enum" <|-- "sasae_flutter_app::models::post::normal_post.dart::NormalPostReactionType"

class "sasae_flutter_app::models::post::poll::poll_option.dart::PollOptionModel" {
  +int id
  +String option
  +List<int> reaction
  +int hashCode
  +PollOptionModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "sasae_flutter_app::models::post::poll::poll_post.dart::PollPostModel" {
  +List<PollOptionModel> polls
  +DateTime? endsOn
  +int? choice
  +String? author
  +int? authorID
  +DateTime createdOn
  +int id
  +bool isAnonymous
  +DateTime? modifiedOn
  +List<NGO__Model> pokedNGO
  +String postContent
  +String postType
  +List<String> relatedTo
  +int hashCode
  +PollPostModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"sasae_flutter_app::models::post::abstract_post.dart::AbstractPostModel" <|-- "sasae_flutter_app::models::post::poll::poll_post.dart::PollPostModel"

class "sasae_flutter_app::models::post::post_.dart::Post_Model" {
  +int id
  +List<String> relatedTo
  +String postContent
  +DateTime postedOn
  +String postType
  +bool isPostedAnonymously
  +bool isPokedToNGO
  +int hashCode
  +Post_Model copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

class "sasae_flutter_app::models::post::post_create_update.dart::NormalPostCUModel" {
  -int? _postID
  -List<String>? _relatedTo
  -String? _postContent
  -bool? _isAnonymous
  -List<int>? _pokedNGO
  -String? _postImageLink
  -XFile? _postImage
  +int? getPostID
  +List<String>? getRelatedTo
  +String? getPostContent
  +bool? getIsAnonymous
  +List<int>? getPokedNGO
  +String? getPostImageLink
  +XFile? getPostImage
  +int? setPostID
  +List<String>? setRelatedTo
  +String? setPostContent
  +bool? setIsAnonymous
  +List<int>? setPokedNGO
  +String? setPostImageLiink
  +XFile? setPostImage
  +int hashCode
  +void nullifyNormal()
  +void nullifyAll()
  +String toString()
  +bool ==()
}

"sasae_flutter_app::models::post::post_create_update.dart::NormalPostCUModel" o-- "cross_file::src::types::interface.dart::XFile"

class "sasae_flutter_app::models::post::post_create_update.dart::PollPostCUModel" {
  -int? _postID
  -List<String>? _relatedTo
  -String? _postContent
  -bool? _isAnonymous
  -List<int>? _pokedNGO
  -List<String>? _pollOptions
  -DateTime? _pollDuration
  +int? getPostID
  +List<String>? getRelatedTo
  +String? getPostContent
  +bool? getIsAnonymous
  +List<int>? getPokedNGO
  +List<String>? getPollOptions
  +DateTime? getPollDuration
  +int? setPostID
  +List<String>? setRelatedTo
  +String? setPostContent
  +bool? setIsAnonymous
  +List<int>? setPokedNGO
  +List<String>? setPollOptions
  +DateTime? setPollDuration
  +int hashCode
  +void nullifyPoll()
  +void nullifyAll()
  +String toString()
  +bool ==()
}

class "sasae_flutter_app::models::post::post_create_update.dart::RequestPostCUModel" {
  -int? _postID
  -List<String>? _relatedTo
  -String? _postContent
  -bool? _isAnonymous
  -List<int>? _pokedNGO
  -int? _min
  -int? _target
  -int? _max
  -String? _requestType
  -DateTime? _requestDuration
  +int? getPostID
  +List<String>? getRelatedTo
  +String? getPostContent
  +bool? getIsAnonymous
  +List<int>? getPokedNGO
  +int? getMin
  +int? getTarget
  +int? getMax
  +String? getRequestType
  +DateTime? getRequestDuration
  +int? setPostID
  +List<String>? setRelatedTo
  +String? setPostContent
  +bool? setIsAnonymous
  +List<int>? setPokedNGO
  +int? setMin
  +int? setTarget
  +int? setMax
  +String? setRequestType
  +DateTime? setRequestDuration
  +int hashCode
  +void nullifyRequest()
  +void nullifyAll()
  +String toString()
  +bool ==()
}

class "sasae_flutter_app::models::post::request_post.dart::RequestPostModel" {
  +int min
  +int target
  +int? max
  +List<int> reaction
  +DateTime endsOn
  +String requestType
  +bool isParticipated
  +String? author
  +int? authorID
  +DateTime createdOn
  +int id
  +bool isAnonymous
  +DateTime? modifiedOn
  +List<NGO__Model> pokedNGO
  +String postContent
  +String postType
  +List<String> relatedTo
  +int hashCode
  +RequestPostModel copyWith()
  +Map<String, dynamic> toMap()
  +String toJson()
  +String toString()
  +bool ==()
}

"sasae_flutter_app::models::post::abstract_post.dart::AbstractPostModel" <|-- "sasae_flutter_app::models::post::request_post.dart::RequestPostModel"

class "sasae_flutter_app::models::user.dart::UserModel" {
  +int id
  +String username
  +bool isVerified
  +String displayPicture
  +String phone
  +String email
  +DateTime joinedDate
  +List<int> postedPosts
}

class "sasae_flutter_app::page_router.dart::PageRouter" {
  +State<PageRouter> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::page_router.dart::PageRouter"

class "sasae_flutter_app::page_router.dart::_PageRouterState" {
  -Future<void> _autoLoginFuture
  -AuthProvider _authP
  +void initState()
  +Future<void> tryAutoLogin()
  +Widget build()
}

"sasae_flutter_app::page_router.dart::_PageRouterState" o-- "sasae_flutter_app::providers::auth_provider.dart::AuthProvider"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::page_router.dart::_PageRouterState"

class "sasae_flutter_app::providers::auth_provider.dart::AuthProvider" {
  -AuthModel? _auth
  -bool _isAuthenticating
  -SessionManager _sessionManager
  +bool isAuth
  +AuthModel? auth
  +bool isAuthenticating
  -Future<void> _authenticate()
  +Future<void> login()
  +Future<void> tryAutoLogin()
  +Future<bool> logout()
  +Future<bool> resetPassword()
  +Future<bool> deleteUser()
  +Future<bool> changePassword()
}

"sasae_flutter_app::providers::auth_provider.dart::AuthProvider" o-- "sasae_flutter_app::models::auth.dart::AuthModel"
"sasae_flutter_app::providers::auth_provider.dart::AuthProvider" o-- "flutter_session_manager::flutter_session_manager.dart::SessionManager"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::auth_provider.dart::AuthProvider"

class "sasae_flutter_app::providers::fab_provider.dart::ProfileSettingFABProvider" {
  -bool _showFAB
  -int _tabIndex
  -UserType? _userType
  -void Function()? _onPressedHandler
  +bool getShowFAB
  +int setTabIndex
  +UserType setUserType
  +bool setShowFAB
  +void Function()? getOnPressedHandler
  +void Function()? setOnPressedHandler
}

"sasae_flutter_app::providers::fab_provider.dart::ProfileSettingFABProvider" o-- "sasae_flutter_app::providers::profile_provider.dart::UserType"
"sasae_flutter_app::providers::fab_provider.dart::ProfileSettingFABProvider" o-- "dart::ui::void Function()"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::fab_provider.dart::ProfileSettingFABProvider"

class "sasae_flutter_app::providers::fab_provider.dart::DonationFABProvider" {
  -bool _showFAB
  -int _tabIndex
  -bool _ngoVerified
  +bool getShowFAB
  +int setTabIndex
  +bool setNGOVerified
  +bool setShowFAB
  +void resetFAB()
}

"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::fab_provider.dart::DonationFABProvider"

class "sasae_flutter_app::providers::fab_provider.dart::PostFABProvider" {
  -bool _showFAB
  -void Function()? _onPressedHandler
  +bool getShowFAB
  +bool setShowFAB
  +void Function()? getOnPressedHandler
  +void Function()? setOnPressedHandler
}

"sasae_flutter_app::providers::fab_provider.dart::PostFABProvider" o-- "dart::ui::void Function()"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::fab_provider.dart::PostFABProvider"

class "sasae_flutter_app::providers::fab_provider.dart::LogoutFABProvider" {
  -bool _showFAB
  -void Function()? _onPressedHandler
  +bool getShowFAB
  +bool setShowFAB
  +void Function()? getOnPressedHandler
  +void Function()? setOnPressedHandler
}

"sasae_flutter_app::providers::fab_provider.dart::LogoutFABProvider" o-- "dart::ui::void Function()"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::fab_provider.dart::LogoutFABProvider"

class "sasae_flutter_app::providers::fab_provider.dart::FABType" {
  +int index
  {static} +List<FABType> values
  {static} +FABType editProfile
  {static} +FABType donation
}

"sasae_flutter_app::providers::fab_provider.dart::FABType" o-- "sasae_flutter_app::providers::fab_provider.dart::FABType"
"dart::core::Enum" <|-- "sasae_flutter_app::providers::fab_provider.dart::FABType"

class "sasae_flutter_app::providers::ngo_provider.dart::NGOProvider" {
  -AuthProvider _authP
  -List<NGO_Model>? _ngos
  -List<NGO_Model>? _ngosToShow
  -Set<String> _fieldOfWork
  -List<String> _selectedFOW
  -bool _isFiltered
  -bool _isSearched
  -bool _isNGOsLoading
  -NGOModel? _ngo
  +AuthProvider setAuthP
  +List<String> setSelectedFOW
  +List<NGO_Model>? getNGOs
  +Set<String> getFieldOfWork
  +List<String> getSelectedFOW
  +bool getFetchError
  +bool getIsFiltered
  +bool getIsSearched
  +bool getIsNGOsLoading
  +NGOModel? getNGO
  -void _randNGOs()
  +Future<void> fetchNGOs()
  +void setRefreshingStatus()
  +Future<void> refreshNGOs()
  -Future<void> _extractFoW()
  +Future<void> searchByName()
  +Future<void> applyFieldOfWorkFilter()
  +void clear()
  {static} +NGOModel randNGO()
  +Future<void> initFetchNGO()
  +Future<void> refreshNGO()
  +void nullifyNGO()
  {static} +Future<NGOModel?> fetchNGO()
}

"sasae_flutter_app::providers::ngo_provider.dart::NGOProvider" o-- "sasae_flutter_app::providers::auth_provider.dart::AuthProvider"
"sasae_flutter_app::providers::ngo_provider.dart::NGOProvider" o-- "sasae_flutter_app::models::ngo.dart::NGOModel"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::ngo_provider.dart::NGOProvider"

class "sasae_flutter_app::providers::notification_provider.dart::NotificationProvider" {
  +JsonStore jsonStore
  -List<NotificationModel> _notifications
  +List<NotificationModel> getNotifications
  -List<NotificationModel> _randNotifications()
  +Future<void> addNotification()
  +Future<void> markRead()
  +Future<void> markAsReadAll()
  +Future<void> clearNotification()
  +Future<void> flushNotifications()
  +Future<void> fetchNotifications()
}

"sasae_flutter_app::providers::notification_provider.dart::NotificationProvider" o-- "json_store::src::json_store.dart::JsonStore"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::notification_provider.dart::NotificationProvider"

class "sasae_flutter_app::providers::page_navigator_provider.dart::PageNavigatorProvider" {
  -int _pageIndex
  -PageController _pageController
  +int getPageIndex
  +PageController getPageController
  +int setPageIndex
  +void initPageController()
  +void navigateToPage()
  +void reset()
}

"sasae_flutter_app::providers::page_navigator_provider.dart::PageNavigatorProvider" o-- "flutter::src::widgets::page_view.dart::PageController"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::page_navigator_provider.dart::PageNavigatorProvider"

class "sasae_flutter_app::providers::people_provider.dart::PeopleProvider" {
  -AuthProvider _authP
  -PeopleModel? _people
  -PeopleUpdateModel? _peopleUpdate
  +PeopleModel? peopleData
  +AuthProvider setAuthP
  +PeopleUpdateModel? getPeopleUpdate
  {static} +PeopleModel randPeople()
  +Future<void> initFetchPeople()
  +Future<void> refreshUser()
  +void nullifyPeople()
  +Future<bool> registerPeople()
  +void nullifyPeopleUpdate()
  +Future<void> retrieveUpdatePeople()
  +Future<void> refreshPeopleUpdate()
  +Future<bool> updatePeople()
  {static} +Future<PeopleModel?> fetchPeople()
}

"sasae_flutter_app::providers::people_provider.dart::PeopleProvider" o-- "sasae_flutter_app::providers::auth_provider.dart::AuthProvider"
"sasae_flutter_app::providers::people_provider.dart::PeopleProvider" o-- "sasae_flutter_app::models::people.dart::PeopleModel"
"sasae_flutter_app::providers::people_provider.dart::PeopleProvider" o-- "sasae_flutter_app::models::people.dart::PeopleUpdateModel"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::people_provider.dart::PeopleProvider"

class "sasae_flutter_app::providers::post_provider.dart::PostProvider" {
  -AuthProvider _authP
  -List<Post_Model>? _posts
  -Dio _dio
  +List<Post_Model>? getPostData
  +AuthProvider setAuthP
  -List<Post_Model> _randPosts()
  +Future<void> intiFetchPosts()
  +Future<List<Post_Model>?> fetchPosts()
  +Future<void> refreshPosts()
  +Future<bool> report()
}

"sasae_flutter_app::providers::post_provider.dart::PostProvider" o-- "sasae_flutter_app::providers::auth_provider.dart::AuthProvider"
"sasae_flutter_app::providers::post_provider.dart::PostProvider" o-- "dio::src::dio.dart::Dio"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::post_provider.dart::PostProvider"

class "sasae_flutter_app::providers::post_provider.dart::PostCreateProvider" {
  -AuthProvider _authP
  -Dio _dio
  -List<String>? _postRelatedTo
  -List<NGO__Model>? _ngoOptions
  -PostType _createPostType
  -Future<void> Function()? _postCreateHandler
  -NormalPostCUModel _normalPostCreate
  -PollPostCUModel _pollPostCreate
  -RequestPostCUModel _requestPostCreate
  +AuthProvider setAuthP
  +List<String>? getPostRelatedToData
  +List<NGO__Model>? getNGOOptionsData
  +PostType getCreatePostType
  +PostType setCreatePostType
  +Future<void> Function()? getPostCreateHandler
  +Future<void> Function()? setPostHandler
  +NormalPostCUModel getNormalPostCreate
  +PollPostCUModel getPollPostCreate
  +RequestPostCUModel getRequestPostCreate
  +Future<void> initPostRelatedTo()
  +Future<void> initNGOOptions()
  +Future<void> refreshPostRelatedTo()
  +Future<void> refreshNGOOptions()
  +Future<List<String>?> getPostRelatedTo()
  +Future<List<NGO__Model>?> getNGOOptions()
  +Future<bool> createNormalPost()
  +Future<bool> createPollPost()
  +Future<bool> createRequestPost()
}

"sasae_flutter_app::providers::post_provider.dart::PostCreateProvider" o-- "sasae_flutter_app::providers::auth_provider.dart::AuthProvider"
"sasae_flutter_app::providers::post_provider.dart::PostCreateProvider" o-- "dio::src::dio.dart::Dio"
"sasae_flutter_app::providers::post_provider.dart::PostCreateProvider" o-- "sasae_flutter_app::providers::post_provider.dart::PostType"
"sasae_flutter_app::providers::post_provider.dart::PostCreateProvider" o-- "null::Future<void> Function()"
"sasae_flutter_app::providers::post_provider.dart::PostCreateProvider" o-- "sasae_flutter_app::models::post::post_create_update.dart::NormalPostCUModel"
"sasae_flutter_app::providers::post_provider.dart::PostCreateProvider" o-- "sasae_flutter_app::models::post::post_create_update.dart::PollPostCUModel"
"sasae_flutter_app::providers::post_provider.dart::PostCreateProvider" o-- "sasae_flutter_app::models::post::post_create_update.dart::RequestPostCUModel"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::post_provider.dart::PostCreateProvider"

class "sasae_flutter_app::providers::post_provider.dart::PostUpdateProvider" {
  -AuthProvider _authP
  -NormalPostCUModel? _normalPostCU
  -PollPostCUModel? _pollPostCU
  -RequestPostCUModel? _requestPostCU
  -PostType? _updatePostType
  -Future<void> Function()? _postUpdateHandler
  +AuthProvider setAuthP
  +NormalPostCUModel? getNormalPostCU
  +PollPostCUModel? getPollPostCU
  +RequestPostCUModel? getRequestPostCU
  +PostType? getUpdatePostType
  +Future<void> Function()? getPostUpdateHandler
  +Future<void> Function()? setPostHandler
  +void nullifyNormalPostCU()
  +void nullifyPollPostCU()
  +void nullifyRequestPostCU()
  +void nullifyPostType()
  +void nullfyPerPostType()
  +Future<void> retrieveUpdatePost()
  +Future<void> refreshRetrieveUpdatePost()
  +Future<bool> updatePost()
}

"sasae_flutter_app::providers::post_provider.dart::PostUpdateProvider" o-- "sasae_flutter_app::providers::auth_provider.dart::AuthProvider"
"sasae_flutter_app::providers::post_provider.dart::PostUpdateProvider" o-- "sasae_flutter_app::models::post::post_create_update.dart::NormalPostCUModel"
"sasae_flutter_app::providers::post_provider.dart::PostUpdateProvider" o-- "sasae_flutter_app::models::post::post_create_update.dart::PollPostCUModel"
"sasae_flutter_app::providers::post_provider.dart::PostUpdateProvider" o-- "sasae_flutter_app::models::post::post_create_update.dart::RequestPostCUModel"
"sasae_flutter_app::providers::post_provider.dart::PostUpdateProvider" o-- "sasae_flutter_app::providers::post_provider.dart::PostType"
"sasae_flutter_app::providers::post_provider.dart::PostUpdateProvider" o-- "null::Future<void> Function()"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::post_provider.dart::PostUpdateProvider"

class "sasae_flutter_app::providers::post_provider.dart::NormalPostProvider" {
  -NormalPostModel? _normalPost
  -AuthProvider _authP
  -Dio _dio
  +AuthProvider setAuthP
  +NormalPostModel? normalPostData
  -NormalPostModel _randNormalPost()
  +Future<void> initFetchNormalPost()
  +Future<NormalPostModel?> fetchNormalPost()
  +Future<void> refreshNormalPost()
  +Future<bool> toggleReaction()
  +void nullifyNormalPost()
}

"sasae_flutter_app::providers::post_provider.dart::NormalPostProvider" o-- "sasae_flutter_app::models::post::normal_post.dart::NormalPostModel"
"sasae_flutter_app::providers::post_provider.dart::NormalPostProvider" o-- "sasae_flutter_app::providers::auth_provider.dart::AuthProvider"
"sasae_flutter_app::providers::post_provider.dart::NormalPostProvider" o-- "dio::src::dio.dart::Dio"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::post_provider.dart::NormalPostProvider"

class "sasae_flutter_app::providers::post_provider.dart::PollPostProvider" {
  -PollPostModel? _pollPost
  -AuthProvider _authP
  -Dio _dio
  +AuthProvider setAuthP
  +PollPostModel? pollPostData
  -PollPostModel _randPollPost()
  +Future<void> initFetchPollPost()
  +Future<PollPostModel?> fetchPollPost()
  +Future<void> refreshPollPost()
  +Future<bool> pollTheOption()
  +void nullifyPollPost()
}

"sasae_flutter_app::providers::post_provider.dart::PollPostProvider" o-- "sasae_flutter_app::models::post::poll::poll_post.dart::PollPostModel"
"sasae_flutter_app::providers::post_provider.dart::PollPostProvider" o-- "sasae_flutter_app::providers::auth_provider.dart::AuthProvider"
"sasae_flutter_app::providers::post_provider.dart::PollPostProvider" o-- "dio::src::dio.dart::Dio"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::post_provider.dart::PollPostProvider"

class "sasae_flutter_app::providers::post_provider.dart::RequestPostProvider" {
  -RequestPostModel? _requestPost
  -AuthProvider _authP
  -Dio _dio
  +AuthProvider setAuthP
  +RequestPostModel? requestPostData
  -RequestPostModel _randRequestPost()
  +Future<void> intiFetchRequestPost()
  +Future<RequestPostModel?> fetchRequestPost()
  +Future<void> refreshRequestPost()
  +Future<bool> participateRequest()
  +void nullifyRequestPost()
}

"sasae_flutter_app::providers::post_provider.dart::RequestPostProvider" o-- "sasae_flutter_app::models::post::request_post.dart::RequestPostModel"
"sasae_flutter_app::providers::post_provider.dart::RequestPostProvider" o-- "sasae_flutter_app::providers::auth_provider.dart::AuthProvider"
"sasae_flutter_app::providers::post_provider.dart::RequestPostProvider" o-- "dio::src::dio.dart::Dio"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::post_provider.dart::RequestPostProvider"

class "sasae_flutter_app::providers::post_provider.dart::PostType" {
  +int index
  {static} +List<PostType> values
  {static} +PostType normal
  {static} +PostType poll
  {static} +PostType request
}

"sasae_flutter_app::providers::post_provider.dart::PostType" o-- "sasae_flutter_app::providers::post_provider.dart::PostType"
"dart::core::Enum" <|-- "sasae_flutter_app::providers::post_provider.dart::PostType"

class "sasae_flutter_app::providers::profile_provider.dart::ProfileProvider" {
  -AuthProvider _authP
  -Dio _dio
  -UserModel? _user
  -List<Post_Model>? _userPosts
  +UserModel? userData
  +List<Post_Model>? getUserPostData
  +AuthProvider setAuthP
  +Future<void> initFetchUser()
  +Future<void> refreshUser()
  +Future<void> intiFetchUserPosts()
  +Future<List<Post_Model>?> fetchUserPosts()
  +Future<void> refreshUserPosts()
  +Future<bool> delete()
}

"sasae_flutter_app::providers::profile_provider.dart::ProfileProvider" o-- "sasae_flutter_app::providers::auth_provider.dart::AuthProvider"
"sasae_flutter_app::providers::profile_provider.dart::ProfileProvider" o-- "dio::src::dio.dart::Dio"
"sasae_flutter_app::providers::profile_provider.dart::ProfileProvider" o-- "sasae_flutter_app::models::user.dart::UserModel"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "sasae_flutter_app::providers::profile_provider.dart::ProfileProvider"

class "sasae_flutter_app::providers::profile_provider.dart::UserType" {
  +int index
  {static} +List<UserType> values
  {static} +UserType people
  {static} +UserType ngo
}

"sasae_flutter_app::providers::profile_provider.dart::UserType" o-- "sasae_flutter_app::providers::profile_provider.dart::UserType"
"dart::core::Enum" <|-- "sasae_flutter_app::providers::profile_provider.dart::UserType"

class "sasae_flutter_app::services::http_client_service.dart::HTTPClientService" {
  {static} -HTTPClientService? _httpcLientService
  -Client _client
  +void init()
  +Client getClient()
  +void closeClient()
}

"sasae_flutter_app::services::http_client_service.dart::HTTPClientService" o-- "sasae_flutter_app::services::http_client_service.dart::HTTPClientService"
"sasae_flutter_app::services::http_client_service.dart::HTTPClientService" o-- "http::src::client.dart::Client"

class "sasae_flutter_app::services::notification_service.dart::NotificationService" {
  {static} -NotificationService? _notificationService
  -FlutterLocalNotificationsPlugin _notificationsPlugin
  +AndroidNotificationChannel channel
  +void initialize()
  +void notify()
}

"sasae_flutter_app::services::notification_service.dart::NotificationService" o-- "sasae_flutter_app::services::notification_service.dart::NotificationService"
"sasae_flutter_app::services::notification_service.dart::NotificationService" o-- "flutter_local_notifications::src::flutter_local_notifications_plugin.dart::FlutterLocalNotificationsPlugin"
"sasae_flutter_app::services::notification_service.dart::NotificationService" o-- "flutter_local_notifications::src::platform_specifics::android::notification_channel.dart::AndroidNotificationChannel"

class "sasae_flutter_app::services::notification_service.dart::NotificationChannel" {
  +int index
  {static} +List<NotificationChannel> values
  {static} +NotificationChannel reaction
  {static} +NotificationChannel poll
  {static} +NotificationChannel join
  {static} +NotificationChannel petition
  {static} +NotificationChannel poke
  {static} +NotificationChannel remove
  {static} +NotificationChannel verify
}

"sasae_flutter_app::services::notification_service.dart::NotificationChannel" o-- "sasae_flutter_app::services::notification_service.dart::NotificationChannel"
"dart::core::Enum" <|-- "sasae_flutter_app::services::notification_service.dart::NotificationChannel"

class "sasae_flutter_app::ui::auth::auth_screen.dart::AuthScreen" {
  {static} +String routeName
  +_AuthScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::auth::auth_screen.dart::AuthScreen"

class "sasae_flutter_app::ui::auth::auth_screen.dart::_AuthScreenState" {
  -GlobalKey<FormBuilderState> _loginFormKey
  -GlobalKey<FormBuilderState> _passwordResetFormKey
  -TextEditingController _userNameTEC
  -TextEditingController _passwordTEC
  -TextEditingController _resetEmailTEC
  +void dispose()
  -Widget _userName()
  -Widget _passwordField()
  -Widget _loginButton()
  -Widget _forgetButton()
  -Widget _createAccountLabel()
  -Widget _logo()
  -Widget _loginForm()
  +Future<void> showResetPasswordModal()
  +Widget build()
}

"sasae_flutter_app::ui::auth::auth_screen.dart::_AuthScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"sasae_flutter_app::ui::auth::auth_screen.dart::_AuthScreenState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::auth::auth_screen.dart::_AuthScreenState"

class "sasae_flutter_app::ui::auth::register_screen.dart::RegisterScreen" {
  {static} +String routeName
  +_RegisterScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::auth::register_screen.dart::RegisterScreen"

class "sasae_flutter_app::ui::auth::register_screen.dart::_RegisterScreenState" {
  -GlobalKey<FormBuilderState> _personalInfoFormKey
  -GlobalKey<FormBuilderState> _addressFormKey
  -GlobalKey<FormBuilderState> _contactFormKey
  -GlobalKey<FormBuilderState> _accountFormKey
  -GlobalKey<FormBuilderState> _verifyFormKey
  -TextEditingController _passwordTEC
  -int _currentStep
  -List<bool> _stepErrors
  -String? _fullname
  -String? _gender
  -DateTime? _birthdate
  -String? _country
  -String? _province
  -String? _cityLocality
  -String? _stAddressHouseNum
  -String? _phone
  -String? _email
  -XFile? _displayPicture
  -String? _username
  -XFile? _citizenshipPhoto
  +void dispose()
  +ListTile getPostModalItem()
  +Widget fullnameField()
  -Widget _genderField()
  -Widget _birthDateField()
  +Widget countryField()
  +Widget provinceField()
  +Widget cityLocalityField()
  +Widget streetHouseField()
  +Widget phoneField()
  +Widget emailField()
  +Widget displayPictureField()
  +Widget usernameField()
  +Widget password1Field()
  +Widget password2Field()
  +Widget citizenshipField()
  +List<Step> getSteps()
  +List<bool Function()> validity()
  +Widget build()
}

"sasae_flutter_app::ui::auth::register_screen.dart::_RegisterScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"sasae_flutter_app::ui::auth::register_screen.dart::_RegisterScreenState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"sasae_flutter_app::ui::auth::register_screen.dart::_RegisterScreenState" o-- "cross_file::src::types::interface.dart::XFile"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::auth::register_screen.dart::_RegisterScreenState"

class "sasae_flutter_app::ui::home_screen.dart::HomePage" {
  {static} +String routeName
  +_HomePageState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::home_screen.dart::HomePage"

class "sasae_flutter_app::ui::home_screen.dart::_HomePageState" {
  -PageNavigatorProvider _pageNavigatorP
  +void initState()
  +void dispose()
  +Widget build()
}

"sasae_flutter_app::ui::home_screen.dart::_HomePageState" o-- "sasae_flutter_app::providers::page_navigator_provider.dart::PageNavigatorProvider"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::home_screen.dart::_HomePageState"

class "sasae_flutter_app::ui::image_view_screen.dart::ImageViewScreen" {
  {static} +String routeName
  +String imageURL
  +String title
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::image_view_screen.dart::ImageViewScreen"

class "sasae_flutter_app::ui::ngo::module::ngo_card.dart::NGOCard" {
  +NGO_Model ngo_
  +Widget build()
}

"sasae_flutter_app::ui::ngo::module::ngo_card.dart::NGOCard" o-- "sasae_flutter_app::models::ngo_.dart::NGO_Model"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::ngo::module::ngo_card.dart::NGOCard"

class "sasae_flutter_app::ui::ngo::module::ngo_donation_button.dart::NGODonationButton" {
  +ScrollController scrollController
  +State<NGODonationButton> createState()
}

"sasae_flutter_app::ui::ngo::module::ngo_donation_button.dart::NGODonationButton" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::ngo::module::ngo_donation_button.dart::NGODonationButton"

class "sasae_flutter_app::ui::ngo::module::ngo_donation_button.dart::_NGODonationButtonState" {
  -TextEditingController _amountTEC
  -GlobalKey<FormBuilderState> _donationFormKey
  +void dispose()
  +void showDonationModalSheet()
  +Widget build()
}

"sasae_flutter_app::ui::ngo::module::ngo_donation_button.dart::_NGODonationButtonState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"sasae_flutter_app::ui::ngo::module::ngo_donation_button.dart::_NGODonationButtonState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::ngo::module::ngo_donation_button.dart::_NGODonationButtonState"

class "sasae_flutter_app::ui::ngo::module::ngo_info_tab.dart::NGOInfoTab" {
  +int ngoID
  +ScrollController scrollController
  +_NGOInfoTabState createState()
}

"sasae_flutter_app::ui::ngo::module::ngo_info_tab.dart::NGOInfoTab" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::ngo::module::ngo_info_tab.dart::NGOInfoTab"

class "sasae_flutter_app::ui::ngo::module::ngo_info_tab.dart::_NGOInfoTabState" {
  -NGOProvider _ngoP
  -DonationFABProvider _donationFABP
  -Future<void> _fetchNGOFUTURE
  +bool wantKeepAlive
  +void initState()
  +void dispose()
  -Future<void> _fetchNGO()
  +Widget build()
}

"sasae_flutter_app::ui::ngo::module::ngo_info_tab.dart::_NGOInfoTabState" o-- "sasae_flutter_app::providers::ngo_provider.dart::NGOProvider"
"sasae_flutter_app::ui::ngo::module::ngo_info_tab.dart::_NGOInfoTabState" o-- "sasae_flutter_app::providers::fab_provider.dart::DonationFABProvider"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::ngo::module::ngo_info_tab.dart::_NGOInfoTabState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "sasae_flutter_app::ui::ngo::module::ngo_info_tab.dart::_NGOInfoTabState"

class "sasae_flutter_app::ui::ngo::module::ngo_list.dart::NGOList" {
  +List<NGO_Model> ngoList
  +State<NGOList> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::ngo::module::ngo_list.dart::NGOList"

class "sasae_flutter_app::ui::ngo::module::ngo_list.dart::_NGOListState" {
  +ScrollController listScroll
  +void dispose()
  +Widget build()
}

"sasae_flutter_app::ui::ngo::module::ngo_list.dart::_NGOListState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::ngo::module::ngo_list.dart::_NGOListState"

class "sasae_flutter_app::ui::ngo::module::search_filter_bar.dart::SearchFilterBar" {
  +State<SearchFilterBar> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::ngo::module::search_filter_bar.dart::SearchFilterBar"

class "sasae_flutter_app::ui::ngo::module::search_filter_bar.dart::_SearchFilterBarState" {
  -TextEditingController _searchTEC
  -NGOProvider _ngoP
  +void initState()
  +void dispose()
  +Future<void> showFilterModal()
  +Widget build()
}

"sasae_flutter_app::ui::ngo::module::search_filter_bar.dart::_SearchFilterBarState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"sasae_flutter_app::ui::ngo::module::search_filter_bar.dart::_SearchFilterBarState" o-- "sasae_flutter_app::providers::ngo_provider.dart::NGOProvider"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::ngo::module::search_filter_bar.dart::_SearchFilterBarState"

class "sasae_flutter_app::ui::ngo::ngo_page.dart::NGOPage" {
  +_NGOPageState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::ngo::ngo_page.dart::NGOPage"

class "sasae_flutter_app::ui::ngo::ngo_page.dart::_NGOPageState" {
  -Future<void> _fetchNGOFUTURE
  +bool wantKeepAlive
  +void initState()
  -Future<void> _fetchNGO()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::ngo::ngo_page.dart::_NGOPageState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "sasae_flutter_app::ui::ngo::ngo_page.dart::_NGOPageState"

class "sasae_flutter_app::ui::ngo::ngo_profile_screen.dart::NGOProfileScreen" {
  {static} +String routeName
  +int ngoID
  +_NGOProfileScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::ngo::ngo_profile_screen.dart::NGOProfileScreen"

class "sasae_flutter_app::ui::ngo::ngo_profile_screen.dart::_NGOProfileScreenState" {
  -ScrollController _infoScrollController
  -ScrollController _postScrollController
  +void dispose()
  +Widget build()
}

"sasae_flutter_app::ui::ngo::ngo_profile_screen.dart::_NGOProfileScreenState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::ngo::ngo_profile_screen.dart::_NGOProfileScreenState"

class "sasae_flutter_app::ui::notification::module::mark_clear_button.dart::MarkClearButton" {
  +ScrollController scrollController
  +State<MarkClearButton> createState()
}

"sasae_flutter_app::ui::notification::module::mark_clear_button.dart::MarkClearButton" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::notification::module::mark_clear_button.dart::MarkClearButton"

class "sasae_flutter_app::ui::notification::module::mark_clear_button.dart::_MarkClearButtonState" {
  +bool showButton
  +void initState()
  +void dispose()
  +void infoListenScroll()
  +void postListenScroll()
  +void show()
  +void hide()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::notification::module::mark_clear_button.dart::_MarkClearButtonState"

class "sasae_flutter_app::ui::notification::module::notification_list.dart::NotificationList" {
  +List<NotificationModel> notifications
  +ScrollController scrollController
  +Widget build()
}

"sasae_flutter_app::ui::notification::module::notification_list.dart::NotificationList" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::notification::module::notification_list.dart::NotificationList"

class "sasae_flutter_app::ui::notification::module::notification_tile.dart::NotificationTile" {
  +NotificationModel notification
  +IconData getIcon()
  +Widget build()
}

"sasae_flutter_app::ui::notification::module::notification_tile.dart::NotificationTile" o-- "sasae_flutter_app::models::notification.dart::NotificationModel"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::notification::module::notification_tile.dart::NotificationTile"

class "sasae_flutter_app::ui::notification::notification_page.dart::NotificationPage" {
  +State<NotificationPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::notification::notification_page.dart::NotificationPage"

class "sasae_flutter_app::ui::notification::notification_page.dart::_NotificationPageState" {
  -ScrollController _scrollController
  -Future<void> _fetchNotificationFUTURE
  -NotificationProvider _notificationP
  +bool wantKeepAlive
  +void initState()
  +void dispose()
  -Future<void> _fetchPost()
  +Widget build()
}

"sasae_flutter_app::ui::notification::notification_page.dart::_NotificationPageState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"sasae_flutter_app::ui::notification::notification_page.dart::_NotificationPageState" o-- "sasae_flutter_app::providers::notification_provider.dart::NotificationProvider"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::notification::notification_page.dart::_NotificationPageState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "sasae_flutter_app::ui::notification::notification_page.dart::_NotificationPageState"

class "sasae_flutter_app::ui::post::module::post_card.dart::PostCard" {
  +Post_Model post
  +bool isActionable
  +Widget build()
}

"sasae_flutter_app::ui::post::module::post_card.dart::PostCard" o-- "sasae_flutter_app::models::post::post_.dart::Post_Model"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::module::post_card.dart::PostCard"

class "sasae_flutter_app::ui::post::module::post_list.dart::PostList" {
  +List<Post_Model> posts
  +ScrollController? scrollController
  +bool isActionable
  +_PostListState createState()
}

"sasae_flutter_app::ui::post::module::post_list.dart::PostList" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::module::post_list.dart::PostList"

class "sasae_flutter_app::ui::post::module::post_list.dart::_PostListState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::module::post_list.dart::_PostListState"

class "sasae_flutter_app::ui::post::post_create_form_screen.dart::PostCreateFormScreen" {
  {static} +String routeName
  +State<PostCreateFormScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_create_form_screen.dart::PostCreateFormScreen"

class "sasae_flutter_app::ui::post::post_create_form_screen.dart::_PostCreateFormScreenState" {
  -Future<void> _fetchrRelatedToOptionsFUTURE
  -Future<void> _fetchNGOOptionsFUTURE
  +Future<void> Function()? postHandler
  +void initState()
  -Future<void> _fetchRelatedToOptions()
  -Future<void> _fetchNGOOptions()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_create_form_screen.dart::_PostCreateFormScreenState" o-- "null::Future<void> Function()"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_create_form_screen.dart::_PostCreateFormScreenState"
"flutter::src::widgets::ticker_provider.dart::SingleTickerProviderStateMixin" <|-- "sasae_flutter_app::ui::post::post_create_form_screen.dart::_PostCreateFormScreenState"

class "sasae_flutter_app::ui::post::post_page.dart::PostPage" {
  +State<PostPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_page.dart::PostPage"

class "sasae_flutter_app::ui::post::post_page.dart::_PostPageState" {
  -ScrollController _scrollController
  -Future<void> _fetchPostFUTURE
  +bool wantKeepAlive
  +void initState()
  +void dispose()
  +void postfabListenScroll()
  -Future<void> _fetchPost()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_page.dart::_PostPageState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_page.dart::_PostPageState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "sasae_flutter_app::ui::post::post_page.dart::_PostPageState"

class "sasae_flutter_app::ui::post::post_type::normal_post_screen.dart::NormalPostScreen" {
  {static} +String routeName
  +int postID
  +_NormalPostScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::normal_post_screen.dart::NormalPostScreen"

class "sasae_flutter_app::ui::post::post_type::normal_post_screen.dart::_NormalPostScreenState" {
  -ScrollController _scrollController
  -NormalPostProvider _provider
  -Future<void> _fetchNormalPostFUTURE
  +void initState()
  -Future<void> _fetchNormalPost()
  +void dispose()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::normal_post_screen.dart::_NormalPostScreenState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"sasae_flutter_app::ui::post::post_type::normal_post_screen.dart::_NormalPostScreenState" o-- "sasae_flutter_app::providers::post_provider.dart::NormalPostProvider"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::normal_post_screen.dart::_NormalPostScreenState"

class "sasae_flutter_app::ui::post::post_type::poll_post_screen.dart::PollPostScreen" {
  {static} +String routeName
  +int postID
  +_PollPostScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::poll_post_screen.dart::PollPostScreen"

class "sasae_flutter_app::ui::post::post_type::poll_post_screen.dart::_PollPostScreenState" {
  -PollPostProvider _provider
  -Future<void> _fetchPollPostFUTURE
  +void initState()
  +void dispose()
  -Future<void> _fetchPollPost()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::poll_post_screen.dart::_PollPostScreenState" o-- "sasae_flutter_app::providers::post_provider.dart::PollPostProvider"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::poll_post_screen.dart::_PollPostScreenState"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::dismissable_tile.dart::DissmissableTile" {
  +String item
  +void Function(String) removeHandler
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::dismissable_tile.dart::DissmissableTile" o-- "null::void Function(String)"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::dismissable_tile.dart::DissmissableTile"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_normal_post.dart::FormCardNormalPost" {
  +bool isUpdateMode
  +GlobalKey<FormBuilderState> formKey
  +State<FormCardNormalPost> createState()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_normal_post.dart::FormCardNormalPost" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_normal_post.dart::FormCardNormalPost"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_normal_post.dart::_FormCardNormalPostState" {
  -NormalPostCUModel _normalPostCU
  +bool wantKeepAlive
  +void initState()
  +void dispose()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_normal_post.dart::_FormCardNormalPostState" o-- "sasae_flutter_app::models::post::post_create_update.dart::NormalPostCUModel"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_normal_post.dart::_FormCardNormalPostState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_normal_post.dart::_FormCardNormalPostState"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_poll_post.dart::FormCardPollPost" {
  +GlobalKey<FormBuilderState> formKey
  +bool isUpdateMode
  +_FormCardPollPostState createState()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_poll_post.dart::FormCardPollPost" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_poll_post.dart::FormCardPollPost"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_poll_post.dart::_FormCardPollPostState" {
  -TextEditingController _itemTEC
  -GlobalKey<FormBuilderState> _optionsAddFormKey
  -PollPostCUModel _pollPostCU
  +bool wantKeepAlive
  +void initState()
  +void dispose()
  +void addItem()
  +void removeItem()
  +Widget pollTextField()
  +Widget addPollButton()
  +Widget polls()
  +Widget datetimeField()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_poll_post.dart::_FormCardPollPostState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_poll_post.dart::_FormCardPollPostState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_poll_post.dart::_FormCardPollPostState" o-- "sasae_flutter_app::models::post::post_create_update.dart::PollPostCUModel"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_poll_post.dart::_FormCardPollPostState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_poll_post.dart::_FormCardPollPostState"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_request_post.dart::FormCardRequestPost" {
  +GlobalKey<FormBuilderState> formKey
  +bool isUpdateMode
  +_FormCardRequestPostState createState()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_request_post.dart::FormCardRequestPost" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_request_post.dart::FormCardRequestPost"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_request_post.dart::_FormCardRequestPostState" {
  -RequestPostCUModel _requestPostCU
  -TextEditingController _minTEC
  -TextEditingController _targetTEC
  -TextEditingController _maxTEC
  +bool wantKeepAlive
  +void initState()
  +void dispose()
  +Widget minField()
  +Widget targetField()
  +Widget maximumField()
  +Widget requestTypeField()
  +Widget datetimeField()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_request_post.dart::_FormCardRequestPostState" o-- "sasae_flutter_app::models::post::post_create_update.dart::RequestPostCUModel"
"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_request_post.dart::_FormCardRequestPostState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_request_post.dart::_FormCardRequestPostState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::form_card_request_post.dart::_FormCardRequestPostState"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::normal_image_attachment_card.dart::NormalImageAttachmentCard" {
  +String imageURL
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::normal_image_attachment_card.dart::NormalImageAttachmentCard"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::normal_voting_bar.dart::VotingBar" {
  +int upvoteCount
  +int downvoteCount
  +bool isUpvoted
  +bool isDownvoted
  +int postID
  +ScrollController scrollController
  +_VotingBarState createState()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::normal_voting_bar.dart::VotingBar" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::normal_voting_bar.dart::VotingBar"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::normal_voting_bar.dart::_VotingBarState" {
  +bool isUpvoted
  +bool isDownvoted
  +int upvoteCount
  +int downvoteCount
  +bool showVotingBar
  +void initState()
  +void dispose()
  +void listenScroll()
  +void show()
  +void hide()
  +Future<void> react()
  +void upvote()
  +void downvote()
  +Widget upvoteCounter()
  +Widget downvoteCounter()
  +Widget upvoteButton()
  +Widget downvoteButton()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::normal_voting_bar.dart::_VotingBarState"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::poll_bar.dart::PollBar" {
  +String title
  +double percent
  +bool isChoice
  +int milliseconds
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::poll_bar.dart::PollBar"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::poll_bar_poll_list.dart::PollBarPollList" {
  +List<PollOptionModel> list
  +Future<void> Function(int) handler
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::poll_bar_poll_list.dart::PollBarPollList" o-- "null::Future<void> Function(int)"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::poll_bar_poll_list.dart::PollBarPollList"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::poll_bar_reveal_list.dart::PollBarRevealList" {
  +List<PollOptionModel> list
  +int? choice
  +int totalReaction()
  +double percent()
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::poll_bar_reveal_list.dart::PollBarRevealList"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::poll_card.dart::PollCard" {
  +List<PollOptionModel> list
  +int? choice
  +DateTime? endsOn
  +_PollCardState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::poll_card.dart::PollCard"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::poll_card.dart::_PollCardState" {
  -int? _choice
  +void initState()
  +Future<void> setChoice()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::poll_card.dart::_PollCardState"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_author_card.dart::PostAuthorCard" {
  +String author
  +State<PostAuthorCard> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_author_card.dart::PostAuthorCard"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_author_card.dart::_PostAuthorCardState" {
  +bool hidePostAuthor
  +void toggleHidePostAuthor()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_author_card.dart::_PostAuthorCardState"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_bar.dart::PostBar" {
  +State<PostBar> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_bar.dart::PostBar"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_bar.dart::_PostBarState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_bar.dart::_PostBarState"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_create_button.dart::PostCreateButton" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_create_button.dart::PostCreateButton"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_create_form.dart::PostCreateForm" {
  {static} +String routeName
  +List<NGO__Model> snapshotNGOList
  +List<String> snapshotRelatedList
  +_PostCreateFormState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_create_form.dart::PostCreateForm"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_create_form.dart::_PostCreateFormState" {
  -NormalPostCUModel _normalPostCreate
  -PollPostCUModel _pollPostCreate
  -RequestPostCUModel _requestPostCreate
  -GlobalKey<FormBuilderState> _superPostKey
  -GlobalKey<FormBuilderState> _requestFormKey
  -GlobalKey<FormBuilderState> _pollFormKey
  -GlobalKey<FormBuilderState> _normalFormKey
  -GlobalKey<ChipsInputState<dynamic>> _chipKey
  +List<int>? pokedNGO
  +void initState()
  +dynamic initFormClass()
  +void setPostCreateOnPressed()
  +void dispose()
  +Widget relatedToField()
  +Widget pokeNGOField()
  +Widget postContentField()
  +Widget anonymousField()
  +Widget superPostFields()
  +Future<void> postHandler()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_create_form.dart::_PostCreateFormState" o-- "sasae_flutter_app::models::post::post_create_update.dart::NormalPostCUModel"
"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_create_form.dart::_PostCreateFormState" o-- "sasae_flutter_app::models::post::post_create_update.dart::PollPostCUModel"
"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_create_form.dart::_PostCreateFormState" o-- "sasae_flutter_app::models::post::post_create_update.dart::RequestPostCUModel"
"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_create_form.dart::_PostCreateFormState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_create_form.dart::_PostCreateFormState" o-- "flutter::src::widgets::framework.dart::GlobalKey<ChipsInputState<dynamic>>"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_create_form.dart::_PostCreateFormState"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_description_card.dart::PostContentCard" {
  +String content
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_description_card.dart::PostContentCard"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_poked_ngo_card.dart::PokedNGOCard" {
  +List<NGO__Model> list
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_poked_ngo_card.dart::PokedNGOCard"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_related_card.dart::PostRelatedCard" {
  +List<String> list
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_related_card.dart::PostRelatedCard"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_tail_card.dart::PostTailCard" {
  +int postID
  +DateTime createdOn
  +DateTime? modifiedOn
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_tail_card.dart::PostTailCard"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_type_row.dart::PostTypeRow" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_type_row.dart::PostTypeRow"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_update_button.dart::PostUpdateButton" {
  +ScrollController scrollController
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_update_button.dart::PostUpdateButton" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_update_button.dart::PostUpdateButton"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_update_form.dart::PostUpdateForm" {
  {static} +String routeName
  +List<NGO__Model> snapshotNGOList
  +List<String> snapshotRelatedList
  +ScrollController? scrollController
  +_PostUpdateFormState createState()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_update_form.dart::PostUpdateForm" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_update_form.dart::PostUpdateForm"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_update_form.dart::_PostUpdateFormState" {
  -dynamic _postHead
  -GlobalKey<FormBuilderState> _superPostKey
  -GlobalKey<FormBuilderState> _requestFormKey
  -GlobalKey<FormBuilderState> _pollFormKey
  -GlobalKey<FormBuilderState> _normalFormKey
  -PostUpdateProvider _postUpdateP
  -GlobalKey<ChipsInputState<dynamic>> _chipKey
  +List<int>? pokedNGO
  +void initState()
  +void setPostUpdateOnPressed()
  +Future<void> postHandler()
  +Widget relatedToField()
  +Widget pokeNGOField()
  +Widget postContentField()
  +Widget anonymousField()
  +Widget superPostFields()
  +Widget getExtension()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_update_form.dart::_PostUpdateFormState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_update_form.dart::_PostUpdateFormState" o-- "sasae_flutter_app::providers::post_provider.dart::PostUpdateProvider"
"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_update_form.dart::_PostUpdateFormState" o-- "flutter::src::widgets::framework.dart::GlobalKey<ChipsInputState<dynamic>>"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::post_update_form.dart::_PostUpdateFormState"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_card.dart::RequestCard" {
  +int min
  +int target
  +int? max
  +int numReaction
  +DateTime endsOn
  +String requestType
  +double? animationDuration
  +State<RequestCard> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_card.dart::RequestCard"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_card.dart::_RequestCardState" {
  -List<LinearCounts> _chartData
  -TooltipBehavior _tooltipBehavior
  +void initState()
  +List<LinearCounts> getChartData()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_card.dart::_RequestCardState" o-- "syncfusion_flutter_charts::src::common::user_interaction::tooltip.dart::TooltipBehavior"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_card.dart::_RequestCardState"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_card.dart::LinearCounts" {
  +String title
  +int count
}

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_fab.dart::RequestFAB" {
  +int postID
  +ScrollController scrollController
  +String requestType
  +DateTime endsOn
  +bool isParticipated
  +Future<void> participate()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_fab.dart::RequestFAB" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_fab.dart::RequestFAB"

class "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_radial_visualization.dart::RequestRadialVisualization" {
  +List<LinearCounts> chartData
  +TooltipBehavior tooltipBehavior
  +double? animationDuration
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_radial_visualization.dart::RequestRadialVisualization" o-- "syncfusion_flutter_charts::src::common::user_interaction::tooltip.dart::TooltipBehavior"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::post::post_type::post_dependent_widgets::request_radial_visualization.dart::RequestRadialVisualization"

class "sasae_flutter_app::ui::post::post_type::request_post_screen.dart::RequestPostScreen" {
  {static} +String routeName
  +int postID
  +_RequestPostScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_type::request_post_screen.dart::RequestPostScreen"

class "sasae_flutter_app::ui::post::post_type::request_post_screen.dart::_RequestPostScreenState" {
  -RequestPostProvider _provider
  -ScrollController _scrollController
  -Future<void> _fetchRequestPostFUTURE
  +void initState()
  -Future<void> _fetchRequestPost()
  +void dispose()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_type::request_post_screen.dart::_RequestPostScreenState" o-- "sasae_flutter_app::providers::post_provider.dart::RequestPostProvider"
"sasae_flutter_app::ui::post::post_type::request_post_screen.dart::_RequestPostScreenState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_type::request_post_screen.dart::_RequestPostScreenState"

class "sasae_flutter_app::ui::post::post_update_form_screen.dart::PostUpdateFormScreen" {
  {static} +String routeName
  +int postID
  +State<PostUpdateFormScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::post::post_update_form_screen.dart::PostUpdateFormScreen"

class "sasae_flutter_app::ui::post::post_update_form_screen.dart::_PostUpdateFormScreenState" {
  -Future<void> _fetchrRelatedToOptionsFUTURE
  -Future<void> _fetchNGOOptionsFUTURE
  -Future<void> _fetchRetrieveUpdatePeopleFUTURE
  -ScrollController _scrollController
  -PostUpdateProvider _postUpdateP
  -PostCreateProvider _postCreateP
  +void initState()
  +void dispose()
  -Future<void> _fetchRelatedToOptions()
  -Future<void> _fetchNGOOptions()
  -Future<void> _fetchRetrieveUpdatePeople()
  +Widget build()
}

"sasae_flutter_app::ui::post::post_update_form_screen.dart::_PostUpdateFormScreenState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"sasae_flutter_app::ui::post::post_update_form_screen.dart::_PostUpdateFormScreenState" o-- "sasae_flutter_app::providers::post_provider.dart::PostUpdateProvider"
"sasae_flutter_app::ui::post::post_update_form_screen.dart::_PostUpdateFormScreenState" o-- "sasae_flutter_app::providers::post_provider.dart::PostCreateProvider"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::post::post_update_form_screen.dart::_PostUpdateFormScreenState"

class "sasae_flutter_app::ui::profile::change_delete_action.dart::ChangeDeleteAction" {
  +bool deletable
  +State<ChangeDeleteAction> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::profile::change_delete_action.dart::ChangeDeleteAction"

class "sasae_flutter_app::ui::profile::change_delete_action.dart::_ChangeDeleteActionState" {
  -GlobalKey<FormBuilderState> _deleteformKey
  -GlobalKey<FormBuilderState> _changeformKey
  -TextEditingController _oldPasswordTEC
  -TextEditingController _newPassword1TEC
  -TextEditingController _newPassword2TEC
  -bool _error
  +void dispose()
  +Future<void> showPasswordChangeModal()
  +Future<void> showDeleteDialog()
  +Widget build()
}

"sasae_flutter_app::ui::profile::change_delete_action.dart::_ChangeDeleteActionState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"sasae_flutter_app::ui::profile::change_delete_action.dart::_ChangeDeleteActionState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::profile::change_delete_action.dart::_ChangeDeleteActionState"

class "sasae_flutter_app::ui::profile::custom_tabbar.dart::CustomTabBar" {
  +ScrollController infoScrollController
  +ScrollController postScrollController
  +EdgeInsets margin
  +State<CustomTabBar> createState()
}

"sasae_flutter_app::ui::profile::custom_tabbar.dart::CustomTabBar" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"sasae_flutter_app::ui::profile::custom_tabbar.dart::CustomTabBar" o-- "flutter::src::painting::edge_insets.dart::EdgeInsets"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::profile::custom_tabbar.dart::CustomTabBar"

class "sasae_flutter_app::ui::profile::custom_tabbar.dart::_CustomTabBarState" {
  +bool showTabBar
  +void initState()
  +void dispose()
  +void infoListenScroll()
  +void postListenScroll()
  +void show()
  +void hide()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::profile::custom_tabbar.dart::_CustomTabBarState"

class "sasae_flutter_app::ui::profile::info_post_tab.dart::InfoPostTab" {
  +Widget infoTab
  +Widget postTab
  +ScrollController infoScrollController
  +ScrollController postScrollController
  +FABType fabType
  +EdgeInsets? tabBarMargin
  +Widget build()
}

"sasae_flutter_app::ui::profile::info_post_tab.dart::InfoPostTab" o-- "flutter::src::widgets::framework.dart::Widget"
"sasae_flutter_app::ui::profile::info_post_tab.dart::InfoPostTab" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"sasae_flutter_app::ui::profile::info_post_tab.dart::InfoPostTab" o-- "sasae_flutter_app::providers::fab_provider.dart::FABType"
"sasae_flutter_app::ui::profile::info_post_tab.dart::InfoPostTab" o-- "flutter::src::painting::edge_insets.dart::EdgeInsets"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::profile::info_post_tab.dart::InfoPostTab"

class "sasae_flutter_app::ui::profile::ngo_profile.dart::NGOProfile" {
  +NGOModel ngoData
  +Widget build()
}

"sasae_flutter_app::ui::profile::ngo_profile.dart::NGOProfile" o-- "sasae_flutter_app::models::ngo.dart::NGOModel"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::profile::ngo_profile.dart::NGOProfile"

class "sasae_flutter_app::ui::profile::people_profile.dart::PeopleProfile" {
  +PeopleModel peopleData
  +Widget build()
}

"sasae_flutter_app::ui::profile::people_profile.dart::PeopleProfile" o-- "sasae_flutter_app::models::people.dart::PeopleModel"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::profile::people_profile.dart::PeopleProfile"

class "sasae_flutter_app::ui::profile::people_profile_edit_form.dart::PeopleProfileEditForm" {
  +PeopleUpdateModel peopleUpdate
  +ScrollController scrollController
  +GlobalKey<FormBuilderState> formKey
  +_PeopleProfileEditFormState createState()
}

"sasae_flutter_app::ui::profile::people_profile_edit_form.dart::PeopleProfileEditForm" o-- "sasae_flutter_app::models::people.dart::PeopleUpdateModel"
"sasae_flutter_app::ui::profile::people_profile_edit_form.dart::PeopleProfileEditForm" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"sasae_flutter_app::ui::profile::people_profile_edit_form.dart::PeopleProfileEditForm" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::profile::people_profile_edit_form.dart::PeopleProfileEditForm"

class "sasae_flutter_app::ui::profile::people_profile_edit_form.dart::_PeopleProfileEditFormState" {
  +Widget fullNameField()
  +Widget genderField()
  +Widget addressField()
  +Widget birthDateField()
  +Widget emailField()
  +Widget phoneField()
  +Widget displayPicture()
  +Widget citizenshipPhoto()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::profile::people_profile_edit_form.dart::_PeopleProfileEditFormState"

class "sasae_flutter_app::ui::profile::people_profile_edit_form.dart::UpdatePicture" {
  +String labelText
  +XFile? picture
  +void Function(List<dynamic>?)? onSavedFunc
  +bool enabled
  +Widget build()
}

"sasae_flutter_app::ui::profile::people_profile_edit_form.dart::UpdatePicture" o-- "cross_file::src::types::interface.dart::XFile"
"sasae_flutter_app::ui::profile::people_profile_edit_form.dart::UpdatePicture" o-- "null::void Function(List<dynamic>)"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::profile::people_profile_edit_form.dart::UpdatePicture"

class "sasae_flutter_app::ui::profile::people_profile_edit_screen.dart::PeopleProfileEditScreen" {
  {static} +String routeName
  +_PeopleProfileEditScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::profile::people_profile_edit_screen.dart::PeopleProfileEditScreen"

class "sasae_flutter_app::ui::profile::people_profile_edit_screen.dart::_PeopleProfileEditScreenState" {
  -ScrollController _scrollController
  -GlobalKey<FormBuilderState> _formKey
  +PeopleProvider peopleP
  -Future<void> _fetchPeopleUpdateFUTURE
  +void initState()
  -Future<void> _fetchPeopleUpdate()
  +void dispose()
  +Widget build()
}

"sasae_flutter_app::ui::profile::people_profile_edit_screen.dart::_PeopleProfileEditScreenState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"sasae_flutter_app::ui::profile::people_profile_edit_screen.dart::_PeopleProfileEditScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormBuilderState>"
"sasae_flutter_app::ui::profile::people_profile_edit_screen.dart::_PeopleProfileEditScreenState" o-- "sasae_flutter_app::providers::people_provider.dart::PeopleProvider"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::profile::people_profile_edit_screen.dart::_PeopleProfileEditScreenState"

class "sasae_flutter_app::ui::profile::user_info_tab.dart::UserInfoTab" {
  +ScrollController scrollController
  +State<UserInfoTab> createState()
}

"sasae_flutter_app::ui::profile::user_info_tab.dart::UserInfoTab" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::profile::user_info_tab.dart::UserInfoTab"

class "sasae_flutter_app::ui::profile::user_info_tab.dart::_UserInfoTabState" {
  -Future<void> _fetchUserFUTURE
  +ProfileSettingFABProvider profileSettingFABP
  +ProfileProvider profileP
  +bool wantKeepAlive
  +void initState()
  +void dispose()
  -Future<void> _fetchUser()
  +void profleEditfabListenScroll()
  +Widget build()
}

"sasae_flutter_app::ui::profile::user_info_tab.dart::_UserInfoTabState" o-- "sasae_flutter_app::providers::fab_provider.dart::ProfileSettingFABProvider"
"sasae_flutter_app::ui::profile::user_info_tab.dart::_UserInfoTabState" o-- "sasae_flutter_app::providers::profile_provider.dart::ProfileProvider"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::profile::user_info_tab.dart::_UserInfoTabState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "sasae_flutter_app::ui::profile::user_info_tab.dart::_UserInfoTabState"

class "sasae_flutter_app::ui::profile::user_post_tab.dart::UserPostTab" {
  +ScrollController? scrollController
  +int? userID
  +UserType? userType
  +bool actionablePost
  +State<UserPostTab> createState()
}

"sasae_flutter_app::ui::profile::user_post_tab.dart::UserPostTab" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"sasae_flutter_app::ui::profile::user_post_tab.dart::UserPostTab" o-- "sasae_flutter_app::providers::profile_provider.dart::UserType"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::profile::user_post_tab.dart::UserPostTab"

class "sasae_flutter_app::ui::profile::user_post_tab.dart::_UserPostTabState" {
  -Future<void> _fetchUserPostFUTURE
  +bool wantKeepAlive
  +void initState()
  +void dispose()
  -Future<void> _fetchProfilePost()
  +void profleCreatefabListenScroll()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::profile::user_post_tab.dart::_UserPostTabState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "sasae_flutter_app::ui::profile::user_post_tab.dart::_UserPostTabState"

class "sasae_flutter_app::ui::profile::user_profile_page.dart::UserProfilePage" {
  +_UserProfilePageState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::profile::user_profile_page.dart::UserProfilePage"

class "sasae_flutter_app::ui::profile::user_profile_page.dart::_UserProfilePageState" {
  -ScrollController _infoScrollController
  -ScrollController _postScrollController
  +bool wantKeepAlive
  +void dispose()
  +Widget build()
}

"sasae_flutter_app::ui::profile::user_profile_page.dart::_UserProfilePageState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::profile::user_profile_page.dart::_UserProfilePageState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "sasae_flutter_app::ui::profile::user_profile_page.dart::_UserProfilePageState"

class "sasae_flutter_app::ui::setting::module::theme_toggle_button.dart::ThemeToggleButton" {
  +State<ThemeToggleButton> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::setting::module::theme_toggle_button.dart::ThemeToggleButton"

class "sasae_flutter_app::ui::setting::module::theme_toggle_button.dart::_ThemeToggleButtonState" {
  -List<bool> _toggleButtonsState
  +void initState()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::setting::module::theme_toggle_button.dart::_ThemeToggleButtonState"

class "sasae_flutter_app::ui::setting::setting_page.dart::SettingScreen" {
  +State<SettingScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::ui::setting::setting_page.dart::SettingScreen"

class "sasae_flutter_app::ui::setting::setting_page.dart::_SettingScreenState" {
  -String _applicationName
  -String _applicationVersion
  -String _applicationLegalese
  -Icon _applicationIcon
  +bool wantKeepAlive
  +void initState()
  +void onPressLogout()
  +Widget about()
  +Widget licenses()
  +Widget darkMode()
  +Widget build()
}

"sasae_flutter_app::ui::setting::setting_page.dart::_SettingScreenState" o-- "flutter::src::widgets::icon.dart::Icon"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::ui::setting::setting_page.dart::_SettingScreenState"
"flutter::src::widgets::automatic_keep_alive.dart::AutomaticKeepAliveClientMixin" <|-- "sasae_flutter_app::ui::setting::setting_page.dart::_SettingScreenState"

class "sasae_flutter_app::ui::splash_screen.dart::SplashScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::ui::splash_screen.dart::SplashScreen"

class "sasae_flutter_app::widgets::misc::custom_appbar.dart::CustomAppBar" {
  +String title
  +List<Widget>? action
  +Size preferredSize
  +_CustomAppBarState createState()
}

"sasae_flutter_app::widgets::misc::custom_appbar.dart::CustomAppBar" o-- "dart::ui::Size"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::widgets::misc::custom_appbar.dart::CustomAppBar"
"flutter::src::widgets::preferred_size.dart::PreferredSizeWidget" <|-- "sasae_flutter_app::widgets::misc::custom_appbar.dart::CustomAppBar"

class "sasae_flutter_app::widgets::misc::custom_appbar.dart::_CustomAppBarState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::widgets::misc::custom_appbar.dart::_CustomAppBarState"

class "sasae_flutter_app::widgets::misc::custom_card.dart::CustomCard" {
  +Widget child
  +double borderRadius
  +double elevation
  +Color? shadowColor
  +Color? cardColor
  +EdgeInsets margin
  +Widget build()
}

"sasae_flutter_app::widgets::misc::custom_card.dart::CustomCard" o-- "flutter::src::widgets::framework.dart::Widget"
"sasae_flutter_app::widgets::misc::custom_card.dart::CustomCard" o-- "dart::ui::Color"
"sasae_flutter_app::widgets::misc::custom_card.dart::CustomCard" o-- "flutter::src::painting::edge_insets.dart::EdgeInsets"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::widgets::misc::custom_card.dart::CustomCard"

class "sasae_flutter_app::widgets::misc::custom_fab.dart::CustomFAB" {
  +String text
  +IconData icon
  +void Function()? func
  +Color? background
  +Color? foreground
  +Widget build()
}

"sasae_flutter_app::widgets::misc::custom_fab.dart::CustomFAB" o-- "flutter::src::widgets::icon_data.dart::IconData"
"sasae_flutter_app::widgets::misc::custom_fab.dart::CustomFAB" o-- "dart::ui::void Function()"
"sasae_flutter_app::widgets::misc::custom_fab.dart::CustomFAB" o-- "dart::ui::Color"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::widgets::misc::custom_fab.dart::CustomFAB"

class "sasae_flutter_app::widgets::misc::custom_image.dart::CustomImage" {
  +String imageURL
  +double? width
  +double? height
  +String title
  +double aspectRatio
  +double radius
  +bool onTapViewImage
  +bool includeHero
  +Widget imageFromURL()
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::widgets::misc::custom_image.dart::CustomImage"

class "sasae_flutter_app::widgets::misc::custom_image_picker.dart::CustomImagePicker" {
  +String title
  +IconData icon
  +void Function(File) setImageFileHandler
  +_CustomImagePickerState createState()
}

"sasae_flutter_app::widgets::misc::custom_image_picker.dart::CustomImagePicker" o-- "flutter::src::widgets::icon_data.dart::IconData"
"sasae_flutter_app::widgets::misc::custom_image_picker.dart::CustomImagePicker" o-- "null::void Function(File)"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::widgets::misc::custom_image_picker.dart::CustomImagePicker"

class "sasae_flutter_app::widgets::misc::custom_image_picker.dart::_CustomImagePickerState" {
  -ImagePicker _picker
  +TextEditingController imagefield
  -File? _image
  +void dispose()
  +ListTile getPostModalItem()
  +Future<dynamic> pickImage()
  +void showPickImageModal()
  +Widget build()
}

"sasae_flutter_app::widgets::misc::custom_image_picker.dart::_CustomImagePickerState" o-- "image_picker::image_picker.dart::ImagePicker"
"sasae_flutter_app::widgets::misc::custom_image_picker.dart::_CustomImagePickerState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"sasae_flutter_app::widgets::misc::custom_image_picker.dart::_CustomImagePickerState" o-- "dart::io::File"
"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::widgets::misc::custom_image_picker.dart::_CustomImagePickerState"

class "sasae_flutter_app::widgets::misc::custom_image_tile.dart::CustomImageTile" {
  +String title
  +String imageURL
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::widgets::misc::custom_image_tile.dart::CustomImageTile"

class "sasae_flutter_app::widgets::misc::custom_info_tile.dart::CustomInfoTile" {
  +IconData? leadingIcon
  +String trailing
  +String? leading
  +void Function()? func
  +State<CustomInfoTile> createState()
}

"sasae_flutter_app::widgets::misc::custom_info_tile.dart::CustomInfoTile" o-- "flutter::src::widgets::icon_data.dart::IconData"
"sasae_flutter_app::widgets::misc::custom_info_tile.dart::CustomInfoTile" o-- "null::void Function()"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::widgets::misc::custom_info_tile.dart::CustomInfoTile"

class "sasae_flutter_app::widgets::misc::custom_info_tile.dart::_CustomInfoTileState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::widgets::misc::custom_info_tile.dart::_CustomInfoTileState"

class "sasae_flutter_app::widgets::misc::custom_loading.dart::CustomLoading" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::widgets::misc::custom_loading.dart::CustomLoading"

class "sasae_flutter_app::widgets::misc::custom_material_tile.dart::CustomMaterialTile" {
  +Widget child
  +double margin
  +void Function()? func
  +double elevation
  +double borderRadius
  +Color? color
  +Color? shadowColor
  +Color? splashColor
  +Widget build()
}

"sasae_flutter_app::widgets::misc::custom_material_tile.dart::CustomMaterialTile" o-- "flutter::src::widgets::framework.dart::Widget"
"sasae_flutter_app::widgets::misc::custom_material_tile.dart::CustomMaterialTile" o-- "null::void Function()"
"sasae_flutter_app::widgets::misc::custom_material_tile.dart::CustomMaterialTile" o-- "dart::ui::Color"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::widgets::misc::custom_material_tile.dart::CustomMaterialTile"

class "sasae_flutter_app::widgets::misc::custom_obscure_text_field.dart::CustomObscureTextField" {
  +TextEditingController? textEditingController
  +String labeltext
  +String? Function(String?)? validators
  +TextInputType keyboardType
  +TextInputAction textInputAction
  +void Function(String?)? onSaved
  +void Function(String?)? onChanged
  +Widget? prefixIcon
  +Color? iconColor
  +State<CustomObscureTextField> createState()
}

"sasae_flutter_app::widgets::misc::custom_obscure_text_field.dart::CustomObscureTextField" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"sasae_flutter_app::widgets::misc::custom_obscure_text_field.dart::CustomObscureTextField" o-- "null::String Function(String)"
"sasae_flutter_app::widgets::misc::custom_obscure_text_field.dart::CustomObscureTextField" o-- "flutter::src::services::text_input.dart::TextInputType"
"sasae_flutter_app::widgets::misc::custom_obscure_text_field.dart::CustomObscureTextField" o-- "flutter::src::services::text_input.dart::TextInputAction"
"sasae_flutter_app::widgets::misc::custom_obscure_text_field.dart::CustomObscureTextField" o-- "null::void Function(String)"
"sasae_flutter_app::widgets::misc::custom_obscure_text_field.dart::CustomObscureTextField" o-- "flutter::src::widgets::framework.dart::Widget"
"sasae_flutter_app::widgets::misc::custom_obscure_text_field.dart::CustomObscureTextField" o-- "dart::ui::Color"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::widgets::misc::custom_obscure_text_field.dart::CustomObscureTextField"

class "sasae_flutter_app::widgets::misc::custom_obscure_text_field.dart::_CustomObscureTextFieldState" {
  -bool _isObscure
  -void _toggleObscure()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::widgets::misc::custom_obscure_text_field.dart::_CustomObscureTextFieldState"

class "sasae_flutter_app::widgets::misc::custom_scroll_animated_fab.dart::CustomScrollAnimatedFAB" {
  +String text
  +IconData icon
  +void Function()? func
  +Color? background
  +Color? foreground
  +ScrollController? scrollController
  +State<CustomScrollAnimatedFAB> createState()
}

"sasae_flutter_app::widgets::misc::custom_scroll_animated_fab.dart::CustomScrollAnimatedFAB" o-- "flutter::src::widgets::icon_data.dart::IconData"
"sasae_flutter_app::widgets::misc::custom_scroll_animated_fab.dart::CustomScrollAnimatedFAB" o-- "dart::ui::void Function()"
"sasae_flutter_app::widgets::misc::custom_scroll_animated_fab.dart::CustomScrollAnimatedFAB" o-- "dart::ui::Color"
"sasae_flutter_app::widgets::misc::custom_scroll_animated_fab.dart::CustomScrollAnimatedFAB" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "sasae_flutter_app::widgets::misc::custom_scroll_animated_fab.dart::CustomScrollAnimatedFAB"

class "sasae_flutter_app::widgets::misc::custom_scroll_animated_fab.dart::_CustomScrollAnimatedFABState" {
  +bool showFAB
  +void initState()
  +void dispose()
  +void listenScrollForFAB()
  +void show()
  +void hide()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "sasae_flutter_app::widgets::misc::custom_scroll_animated_fab.dart::_CustomScrollAnimatedFABState"

class "sasae_flutter_app::widgets::misc::fetch_error.dart::FetchError" {
  +double fraction
  +String errorMessage
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::widgets::misc::fetch_error.dart::FetchError"

class "sasae_flutter_app::widgets::misc::verified_chip.dart::VerifiedChip" {
  +bool isVerified
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "sasae_flutter_app::widgets::misc::verified_chip.dart::VerifiedChip"


@enduml